name:                aoc2019
version:             0.1.0.0
github:              "mstksg/advent-of-code-2019"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) Justin Le 2019"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            "Development environment for Advent of Code challenges"
category:            Web

description: |
  Scaffolding for an integrated development environment for Advent of Code
  challenges.  Includes auto-runner, prompt displays and countdowns, and
  integrated submissions.

ghc-options:
- -Wall
- -Wcompat
- -Wno-partial-type-signatures
- -Wredundant-constraints

default-extensions:
- AllowAmbiguousTypes
- ApplicativeDo
- BangPatterns
- BlockArguments
- DataKinds
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- ImplicitParams
- KindSignatures
- LambdaCase
- MonadComprehensions
- MultiParamTypeClasses
- MultiWayIf
- NumDecimals
- OverloadedLabels
- PartialTypeSignatures
- PatternGuards
- PatternSynonyms
- PolyKinds
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeInType
- TypeOperators
- UndecidableInstances
- ViewPatterns

dependencies:
- base >= 4.7 && < 5
- mtl

library:
  source-dirs: src
  dependencies:
  - adjunctions
  - advent-of-code-api >= 0.2.7
  - advent-of-code-ocr
  - aeson
  - ansi-terminal
  - array
  - astar
  - bytestring
  - carray
  - comonad
  - conduino >= 0.2.1.0
  - conduit
  - containers
  - criterion
  - data-default-class
  - data-memocombinators
  - deepseq
  - directory
  - fft
  - fgl
  - filepath
  - finite-typelits
  - foldl
  - free
  - generic-lens
  - ghc-typelits-knownnat
  - ghc-typelits-natnormalise
  - graphviz
  - groups
  - hashable
  - haskeline
  - haskell-names
  - haskell-src-exts
  - heredoc
  - hmatrix
  - hpack
  - lens
  - lens-regex-pcre
  - linear
  - megaparsec >= 8.0
  - monad-loops
  - mtl
  - nonempty-containers >= 0.3.3.0
  - one-liner-instances
  - pandoc
  - parallel
  - parsec
  - parser-combinators >= 1.2.0
  - primitive
  - profunctors
  - psqueues
  - recursion-schemes
  - safe
  - semigroupoids
  - sparse-linear-algebra
  - split
  - template-haskell
  - text
  - th-abstraction
  - time
  - transformers
  - unordered-containers
  - vector
  - vector-sized
  - vty
  - witherable
  - yaml

executables:
  aoc2019:
    main:                aoc.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -j4
    dependencies:
    - ansi-terminal
    - aoc2019
    - containers
    - deepseq
    - finite-typelits
    - lens
    - optparse-applicative
  intcode:
    main:                intcode.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -j4
    dependencies:
    # - ansi-terminal
    - aoc2019
    # - containers
    # - deepseq
    # - finite-typelits
    # - lens
    # - optparse-applicative

tests:
  aoc2019-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2019
    - ansi-terminal

benchmarks:
  aoc2019-bench:
    main: Bench.hs
    source-dirs: bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - aoc2019
